### PR TITLE
Add impstats settings

### PR DESCRIPTION
**Pull request by wesleyarthur**
I would like to add impstats

### CODE REVIEW

**Comment by wesleyarthur** [comment]
How does this get merged?

**Comment by aboe76** [comment]
@wesleyarthur Most of the time we let two people review this and then merge it.
Will ask @myii to review it too, then I will merge it.

**Comment by wesleyarthur** [comment]
ahh ok. thanks! i'm new to syslog so you might want to review it thoroughly :)

**Comment by myii** [comment]
@wesleyarthur I'm a bit busy at the moment but I'll try to find time for this soon.  In the meanwhile, I've had a quick scan and it appears that all of the defaults could be added to [`defaults.yaml`](https://github.com/saltstack-formulas/rsyslog-formula/blob/master/rsyslog/defaults.yaml) instead.  Then [`map.jinja`](https://github.com/saltstack-formulas/rsyslog-formula/blob/master/rsyslog/map.jinja) will merge any pillar values, if available.

**Comment by wesleyarthur** [comment]
Ok. I have not used defaults before so I'm just trying to figure out the syntax today.

**Comment by aboe76** [comment]
@myii no other config defaults are in the defaults.yml, only salt state variables. So if if you don't mind I'll merge this, we can later create the defaults for configuration in the defaults.yml.

**Comment by wesleyarthur** [comment]
Quick question. Where does the "config." in the jinja file come from?

**Comment by aboe76** [comment]
@wesleyarthur at the moment the config key within the jinja template file comes from the following salt call: salt['pillar.get']['rsyslog']

which translates into look in pillar under the key `rsyslog`

**Comment by aboe76** [comment]
@wesleyarthur which makes what @myii asked rather difficult, because the defaults.yml also exports the key `rsyslog` which defines all salt state configuration, and not the template configuration data.

**Comment by myii** [comment]
@wesleyarthur Sorry for the run around, I didn't get a chance to look in detail.  Thanks for your contribution!  Just to explain: in many formulas, default values are collected in `defaults.yaml`, which then have the pillar values merged on top of them in `map.jinja`.

@aboe76 Lack of familiarity with this formula.  Thank you for stepping in to explain what's taking place here.

**Comment by aboe76** [comment]
@myii no problem

**Comment by wesleyarthur** [comment]
Ok. If there are any good formula examples that use a defaults.yaml well, and documentation that you could point me towards I could try and add that too.

**Comment by myii** [comment]
@wesleyarthur We try to collect the our best practices into the `template-formula`.  Otherwise, there are a number of well-established formulas: `salt`, `nginx`, `mysql`, `users` and `docker` to mention a few.  Another way to have a look is to open https://github.com/saltstack-formulas and then look at the formula listing (ordered by modification date).  Pretty much all of the formulas do this (`defaults.yaml`, etc.).

**Pull request merged**
